#!/usr/bin/python3

import dbus

bus = dbus.SystemBus()

leds = dbus.Interface(bus.get_object('org.thinkglobally.Gemian.LEDs', '/org/thinkglobally/Gemian/LEDs'),
						'org.thinkglobally.Gemian.LEDs')

leds.SetTorch(0,0)
